import Link from "next/link"
import { ReactNode } from "react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  themeColor: "#ffffff",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode,
}) {
  return (
    <html lang="ja">
      <head />
      <body>
        <header>
        <h1>
          <Link href="/">ブログ</Link>
        </h1>
        <Link href="/articles/new">記事を書く</Link>
        </header>
      </body>
      {children}
      <footer>
        <small>© 2023 ryo-manba</small>
      </footer>
    </html>
  )
}